
module.exports.notif_enums = {
    SUBSCRIPTION_REQ_SENT: 'SUBSCRIPTION_REQ_SENT',
    SUBSCRIPTION_REQ_APPROVED: 'SUBSCRIPTION_REQ_APPROVED',
    SUBSCRIPTION_REQ_REJECTED: 'SUBSCRIPTION_REQ_REJECTED'
}